version: '2'
services:
  riddleapplication-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/RiddleApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=RiddleApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
